FROM fedora:rawhide AS build-stage

RUN dnf install -y rpm-build rpmdevtools dnf-plugins-core python3-pip nano rust-packaging

WORKDIR /root/rpmbuild

RUN mkdir -p {BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
COPY rulec.rawhide.spec        SPECS/rulec.spec

RUN dnf builddep SPECS/rulec.spec -y

COPY crates.tar.gz SOURCES/
COPY rulec.tar.gz  SOURCES/
COPY build.sh      ./

WORKDIR /root/rpmbuild

