on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Install git
        run: |
          sudo apt install -y git

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.58.1
          override: true

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Strip ref to tag
        id: tag_name
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d/ -f3)

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r lock2spec.requirements.txt
          cargo install cargo-vendor-filterer

      - name: Vendor
        run: |
          git archive HEAD -o rulec.tar.gz --prefix=example-python-rust-copr
          ./vendor.sh

      - name: Export files
        run: |
          mkdir /tmp/archives
          mv rulec.tar.gz /tmp/archives
          mv crates.tar.gz /tmp/archives

      - uses: softprops/action-gh-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.tag_name.outputs.VERSION }}
          tag_name: ${{ steps.tag_name.outputs.VERSION }}
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, 'rc') }}
          draft: true
          files: /tmp/archives/*
